### ISSUE TITLE
Feature request: efficiently permute a vector

### ISSUE THREAD

**Issue by LilithHafner** [scheinerman/Permutations.jl#26]
That is, compile a permutation to something that can be efficiently applied to multiple vectors (e.g. cycle annotation). For example,
```julia
# permute a vector `v` based on a permutation `p` listed in cycle notation
function cycle_permute!(v::AbstractVector, cycles::AbstractVector{<:AbstractVector})
    for cycle in cycles
        fst = v[first(cycle)]
        for i in firstindex(cycle):lastindex(cycle)-1
            v[cycle[i]] = v[cycle[i+1]]
        end
        v[last(cycle)] = fst
    end
    v
end
```
Is a decent bit faster than `Base.permute!`.

**Comment by scheinerman** [comment]
@LilithHafner : Thank you for your various suggestions. I'm not sure when I'm going to be able to look carefully at these (traveling this past weekend and an overfull week ahead) but I will try to soon.

**Comment by LilithHafner** [comment]
There's no hurry. If you decide to add this, I've got a sample implementation [headed to DataFrames](https://github.com/JuliaData/DataFrames.jl/pull/3035).
