### ISSUE TITLE
Where did the readme go?

### ISSUE THREAD

**Issue by MarcusTL12** [scheinerman/Permutations.jl#30]
Last I used this package I seem to remember a nice readme with examples. Now it only contains to links that lead to 404 not found.

**Comment by scheinerman** [comment]
Ack. Someone did me a favor by moving the README content into something clever, and now I don't know how to resurrect it. In the mean time, it is available here: 
[https://github.com/scheinerman/Permutations.jl/blob/master/docs/src/index.md](https://github.com/scheinerman/Permutations.jl/blob/master/docs/src/index.md
)

Let me try to fix this. Sorry!!

**Comment by scheinerman** [comment]
I've updated the README file so the documentation is on the main page here on github. I have no idea how to maintain the "smarter" documentation.

**Comment by MarcusTL12** [comment]
Thank you very much! :)
