### ISSUE TITLE
Ewens permutations 

### ISSUE THREAD

**Issue by SimonCoste** [scheinerman/Permutations.jl#36]
Hi, 
I often have to use randomly generated permutations, but with a non-uniform distribution called the [Ewens distribution](https://en.wikipedia.org/wiki/Ewens%27s_sampling_formula). I already have my own code and would like to make it available; would `Permutations.jl` be the right place for such an addition ? If yes, I'll add my own branch in the next weeks. If no, do not hesitate to tell me a better package where you think Ewens sampler would better fit !
Best, 
Simon

Edit : btw, thanks for `Permutations.jl` !!!

**Comment by scheinerman** [comment]
Hi @SimonCoste , I'm glad you're finding `Permutations` useful. What I sometimes do is put code that's interesting but not "core" into a separate folder I name `extras`, and note it in the `README` file. So it's not loaded by `using Permutations`, but available to people who might be interested. Would that be an OK way to add your work to this repository? Thanks, Ed

**Comment by scheinerman** [comment]
@SimonCoste would you mind drafting a short README that I can add to the `extras` folder, perhaps with an example?

**Comment by SimonCoste** [comment]
Hi Ed, actually I'll be done shortly, see [the branch on my fork](https://github.com/SimonCoste/Permutations.jl/tree/ewens-random-permutations). I'll add tests to my branch very soon and a decent documentation on the Ewens sampler (it uses the Chinese Restaurant Process, I still need to check everything is ok). I will probably do the PR on friday. 
Best, 
Simon
